// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:8834432b-346c-4712-ae23-d9c01b1edb1f",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_UJ86iUnCi",
    "aws_user_pools_web_client_id": "1jqrqmp37dr0skdfs2bi0r0e5r",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://plghcc5m0m.execute-api.eu-west-1.amazonaws.com/cnlpdev",
            "region": "eu-west-1"
        }
    ],
    "aws_user_files_s3_bucket": "cnlp-data193453-cnlpdev",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
