name: perform-security-checks-dev-prod
on:
  deployment_status:
    branches:
      - master
jobs:
  owasp:
    name: OWASP Scan Prod
    runs-on: ubuntu-latest
    steps:
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: "https://controls.atreides.ai/"
